// Code generated by glitch. DO NOT EDIT!
package gerrors

import "github.com/kalifun/glitch/repo/gerr"

var invalidConfigErr = gerr.ErrWrapper{
	Key:      "InvalidConfig",
	Code:     "InvalidConfig",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "无效配置: %s",
		"en": "Invalid configuration: %s",
	},
	Description: "invalid navlink client configuration",
}

var clientNotStartedErr = gerr.ErrWrapper{
	Key:      "ClientNotStarted",
	Code:     "ClientNotStarted",
	Category: "system",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "客户端未启动",
		"en": "Client is not started",
	},
	Description: "navlink client has not been started",
}

var clientAlreadyStartedErr = gerr.ErrWrapper{
	Key:      "ClientAlreadyStarted",
	Code:     "ClientAlreadyStarted",
	Category: "system",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Client is already started",
		"cn": "客户端已启动",
	},
	Description: "navlink client is already started",
}

var decodeFailedErr = gerr.ErrWrapper{
	Key:      "DecodeFailed",
	Code:     "DecodeFailed",
	Category: "protocol",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "解码失败: %s",
		"en": "Decode failed: %s",
	},
	Description: "failed to decode VDA5050 payload",
}

var identityMismatchErr = gerr.ErrWrapper{
	Key:      "IdentityMismatch",
	Code:     "IdentityMismatch",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Identity mismatch between topic and payload header",
		"cn": "身份不一致: topic 与报文 header 不匹配",
	},
	Description: "topic identity does not match payload header",
}

var idAllocationFailedErr = gerr.ErrWrapper{
	Key:      "IdAllocationFailed",
	Code:     "IdAllocationFailed",
	Category: "system",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "ID allocation failed: %s",
		"cn": "ID 分配失败: %s",
	},
	Description: "failed to allocate outbound protocol id",
}

var mQTTTransportNotRunningErr = gerr.ErrWrapper{
	Key:      "MQTTTransportNotRunning",
	Code:     "TransportNotRunning",
	Category: "system",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "MQTT transport is not running",
		"cn": "MQTT transport 未启动",
	},
	Description: "mqtt transport not running",
}

var mQTTTransportAlreadyRunningErr = gerr.ErrWrapper{
	Key:      "MQTTTransportAlreadyRunning",
	Code:     "TransportAlreadyRunning",
	Category: "system",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "MQTT转换器已经启动",
		"en": "MQTT transport already running",
	},
	Description: "mqtt transport already running",
}

var connectionFailedErr = gerr.ErrWrapper{
	Key:      "ConnectionFailed",
	Code:     "ConnectionFailed",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Failed to connect to MQTT broker",
		"cn": "连接MQTT代理失败",
	},
	Description: "failed to connect to mqtt broker",
}

var authenticationFailedErr = gerr.ErrWrapper{
	Key:      "AuthenticationFailed",
	Code:     "AuthenticationFailed",
	Category: "security",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "MQTT authentication failed",
		"cn": "MQTT认证失败",
	},
	Description: "mqtt authentication failed",
}

var subscriptionFailedErr = gerr.ErrWrapper{
	Key:      "SubscriptionFailed",
	Code:     "SubscriptionFailed",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Failed to subscribe to topic",
		"cn": "订阅主题失败",
	},
	Description: "failed to subscribe to topic",
}

var publishFailedErr = gerr.ErrWrapper{
	Key:      "PublishFailed",
	Code:     "PublishFailed",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "发布消息失败",
		"en": "Failed to publish message",
	},
	Description: "failed to publish message",
}

var invalidTopicErr = gerr.ErrWrapper{
	Key:      "InvalidTopic",
	Code:     "InvalidTopic",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "无效的MQTT主题格式",
		"en": "Invalid MQTT topic format",
	},
	Description: "invalid mqtt topic format",
}

var clientNotConnectedErr = gerr.ErrWrapper{
	Key:      "ClientNotConnected",
	Code:     "ClientNotConnected",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "MQTT client is not connected",
		"cn": "MQTT客户端未连接",
	},
	Description: "mqtt client is not connected",
}

var reconnectFailedErr = gerr.ErrWrapper{
	Key:      "ReconnectFailed",
	Code:     "ReconnectFailed",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "重新连接代理失败",
		"en": "Failed to reconnect to broker",
	},
	Description: "failed to reconnect to broker",
}

var tLSConfigErrorErr = gerr.ErrWrapper{
	Key:      "TLSConfigError",
	Code:     "TLSConfigError",
	Category: "security",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "TLS配置无效",
		"en": "Invalid TLS configuration",
	},
	Description: "invalid tls configuration",
}

var willMessageErrorErr = gerr.ErrWrapper{
	Key:      "WillMessageError",
	Code:     "WillMessageError",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Invalid will message configuration",
		"cn": "遗嘱消息配置无效",
	},
	Description: "invalid will message configuration",
}

var qosNotSupportedErr = gerr.ErrWrapper{
	Key:      "QosNotSupported",
	Code:     "QosNotSupported",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Requested QoS level not supported",
		"cn": "不支持的QoS级别",
	},
	Description: "requested qos level not supported",
}

var messageTooLargeErr = gerr.ErrWrapper{
	Key:      "MessageTooLarge",
	Code:     "MessageTooLarge",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "消息大小超过限制",
		"en": "Message size exceeds limit",
	},
	Description: "message size exceeds limit",
}

var brokerUnavailableErr = gerr.ErrWrapper{
	Key:      "BrokerUnavailable",
	Code:     "BrokerUnavailable",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "MQTT代理不可用",
		"en": "MQTT broker is unavailable",
	},
	Description: "mqtt broker is unavailable",
}

var protocolErrorErr = gerr.ErrWrapper{
	Key:      "ProtocolError",
	Code:     "ProtocolError",
	Category: "protocol",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "MQTT protocol error",
		"cn": "MQTT协议错误",
	},
	Description: "mqtt protocol error",
}

var timeoutErrorErr = gerr.ErrWrapper{
	Key:      "TimeoutError",
	Code:     "TimeoutError",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Operation timed out",
		"cn": "操作超时",
	},
	Description: "operation timed out",
}

var alreadySubscribedErr = gerr.ErrWrapper{
	Key:      "AlreadySubscribed",
	Code:     "AlreadySubscribed",
	Category: "validation",
	Severity: gerr.SeverityWarning,
	Messages: map[string]string{
		"cn": "已经订阅该主题",
		"en": "Already subscribed to topic",
	},
	Description: "already subscribed to topic",
}

var notSubscribedErr = gerr.ErrWrapper{
	Key:      "NotSubscribed",
	Code:     "NotSubscribed",
	Category: "validation",
	Severity: gerr.SeverityWarning,
	Messages: map[string]string{
		"cn": "未订阅该主题",
		"en": "Not subscribed to topic",
	},
	Description: "not subscribed to topic",
}

var invalidPayloadErr = gerr.ErrWrapper{
	Key:      "InvalidPayload",
	Code:     "InvalidPayload",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "无效的消息负载",
		"en": "Invalid message payload",
	},
	Description: "invalid message payload",
}

var configurationErrorErr = gerr.ErrWrapper{
	Key:      "ConfigurationError",
	Code:     "ConfigurationError",
	Category: "validation",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"cn": "MQTT配置无效: %s",
		"en": "Invalid MQTT configuration: %s",
	},
	Description: "invalid mqtt configuration",
}

var subscriptionNotActiveErr = gerr.ErrWrapper{
	Key:      "SubscriptionNotActive",
	Code:     "SubscriptionNotActive",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Subscription to topic %s is not active",
		"cn": "主题 %s 的订阅未激活",
	},
	Description: "subscription to topic is not active",
}

var unsubscribeFailedErr = gerr.ErrWrapper{
	Key:      "UnsubscribeFailed",
	Code:     "UnsubscribeFailed",
	Category: "network",
	Severity: gerr.SeverityError,
	Messages: map[string]string{
		"en": "Failed to unsubscribe from topic %s: %v",
		"cn": "取消订阅主题 %s 失败: %v",
	},
	Description: "failed to unsubscribe from topic",
}

// InvalidConfig represents invalid navlink client configuration
var InvalidConfig = gerr.NewError(invalidConfigErr)

// ClientNotStarted represents navlink client has not been started
var ClientNotStarted = gerr.NewError(clientNotStartedErr)

// ClientAlreadyStarted represents navlink client is already started
var ClientAlreadyStarted = gerr.NewError(clientAlreadyStartedErr)

// DecodeFailed represents failed to decode VDA5050 payload
var DecodeFailed = gerr.NewError(decodeFailedErr)

// IdentityMismatch represents topic identity does not match payload header
var IdentityMismatch = gerr.NewError(identityMismatchErr)

// IdAllocationFailed represents failed to allocate outbound protocol id
var IdAllocationFailed = gerr.NewError(idAllocationFailedErr)

// MQTTTransportNotRunning represents mqtt transport not running
var MQTTTransportNotRunning = gerr.NewError(mQTTTransportNotRunningErr)

// MQTTTransportAlreadyRunning represents mqtt transport already running
var MQTTTransportAlreadyRunning = gerr.NewError(mQTTTransportAlreadyRunningErr)

// ConnectionFailed represents failed to connect to mqtt broker
var ConnectionFailed = gerr.NewError(connectionFailedErr)

// AuthenticationFailed represents mqtt authentication failed
var AuthenticationFailed = gerr.NewError(authenticationFailedErr)

// SubscriptionFailed represents failed to subscribe to topic
var SubscriptionFailed = gerr.NewError(subscriptionFailedErr)

// PublishFailed represents failed to publish message
var PublishFailed = gerr.NewError(publishFailedErr)

// InvalidTopic represents invalid mqtt topic format
var InvalidTopic = gerr.NewError(invalidTopicErr)

// ClientNotConnected represents mqtt client is not connected
var ClientNotConnected = gerr.NewError(clientNotConnectedErr)

// ReconnectFailed represents failed to reconnect to broker
var ReconnectFailed = gerr.NewError(reconnectFailedErr)

// TLSConfigError represents invalid tls configuration
var TLSConfigError = gerr.NewError(tLSConfigErrorErr)

// WillMessageError represents invalid will message configuration
var WillMessageError = gerr.NewError(willMessageErrorErr)

// QosNotSupported represents requested qos level not supported
var QosNotSupported = gerr.NewError(qosNotSupportedErr)

// MessageTooLarge represents message size exceeds limit
var MessageTooLarge = gerr.NewError(messageTooLargeErr)

// BrokerUnavailable represents mqtt broker is unavailable
var BrokerUnavailable = gerr.NewError(brokerUnavailableErr)

// ProtocolError represents mqtt protocol error
var ProtocolError = gerr.NewError(protocolErrorErr)

// TimeoutError represents operation timed out
var TimeoutError = gerr.NewError(timeoutErrorErr)

// AlreadySubscribed represents already subscribed to topic
var AlreadySubscribed = gerr.NewError(alreadySubscribedErr)

// NotSubscribed represents not subscribed to topic
var NotSubscribed = gerr.NewError(notSubscribedErr)

// InvalidPayload represents invalid message payload
var InvalidPayload = gerr.NewError(invalidPayloadErr)

// ConfigurationError represents invalid mqtt configuration
var ConfigurationError = gerr.NewError(configurationErrorErr)

// SubscriptionNotActive represents subscription to topic is not active
var SubscriptionNotActive = gerr.NewError(subscriptionNotActiveErr)

// UnsubscribeFailed represents failed to unsubscribe from topic
var UnsubscribeFailed = gerr.NewError(unsubscribeFailedErr)

func init() {
	if err := gerr.Register(invalidConfigErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(clientNotStartedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(clientAlreadyStartedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(decodeFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(identityMismatchErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(idAllocationFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(mQTTTransportNotRunningErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(mQTTTransportAlreadyRunningErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(connectionFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(authenticationFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(subscriptionFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(publishFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(invalidTopicErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(clientNotConnectedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(reconnectFailedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(tLSConfigErrorErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(willMessageErrorErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(qosNotSupportedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(messageTooLargeErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(brokerUnavailableErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(protocolErrorErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(timeoutErrorErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(alreadySubscribedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(notSubscribedErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(invalidPayloadErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(configurationErrorErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(subscriptionNotActiveErr); err != nil {
		panic(err)
	}
	if err := gerr.Register(unsubscribeFailedErr); err != nil {
		panic(err)
	}
}

// InvalidConfigF indicates this error requires format arguments
// Usage: InvalidConfigF.Args("ErrMessage")
var InvalidConfigF = InvalidConfig

// NewInvalidConfigWithArgs creates a InvalidConfig error with arguments
func NewInvalidConfigWithArgs(args ...interface{}) *gerr.Error {
	return InvalidConfig.Args(args...)
}

// NewInvalidConfigWithMetadata creates a InvalidConfig error with metadata
func NewInvalidConfigWithMetadata(key string, value interface{}) *gerr.Error {
	return InvalidConfig.With(key, value)
}

// NewClientNotStartedWithMetadata creates a ClientNotStarted error with metadata
func NewClientNotStartedWithMetadata(key string, value interface{}) *gerr.Error {
	return ClientNotStarted.With(key, value)
}

// NewClientAlreadyStartedWithMetadata creates a ClientAlreadyStarted error with metadata
func NewClientAlreadyStartedWithMetadata(key string, value interface{}) *gerr.Error {
	return ClientAlreadyStarted.With(key, value)
}

// DecodeFailedF indicates this error requires format arguments
// Usage: DecodeFailedF.Args("ErrMessage")
var DecodeFailedF = DecodeFailed

// NewDecodeFailedWithArgs creates a DecodeFailed error with arguments
func NewDecodeFailedWithArgs(args ...interface{}) *gerr.Error {
	return DecodeFailed.Args(args...)
}

// NewDecodeFailedWithMetadata creates a DecodeFailed error with metadata
func NewDecodeFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return DecodeFailed.With(key, value)
}

// NewIdentityMismatchWithMetadata creates a IdentityMismatch error with metadata
func NewIdentityMismatchWithMetadata(key string, value interface{}) *gerr.Error {
	return IdentityMismatch.With(key, value)
}

// IdAllocationFailedF indicates this error requires format arguments
// Usage: IdAllocationFailedF.Args("ErrMessage")
var IdAllocationFailedF = IdAllocationFailed

// NewIdAllocationFailedWithArgs creates a IdAllocationFailed error with arguments
func NewIdAllocationFailedWithArgs(args ...interface{}) *gerr.Error {
	return IdAllocationFailed.Args(args...)
}

// NewIdAllocationFailedWithMetadata creates a IdAllocationFailed error with metadata
func NewIdAllocationFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return IdAllocationFailed.With(key, value)
}

// NewMQTTTransportNotRunningWithMetadata creates a MQTTTransportNotRunning error with metadata
func NewMQTTTransportNotRunningWithMetadata(key string, value interface{}) *gerr.Error {
	return MQTTTransportNotRunning.With(key, value)
}

// NewMQTTTransportAlreadyRunningWithMetadata creates a MQTTTransportAlreadyRunning error with metadata
func NewMQTTTransportAlreadyRunningWithMetadata(key string, value interface{}) *gerr.Error {
	return MQTTTransportAlreadyRunning.With(key, value)
}

// NewConnectionFailedWithMetadata creates a ConnectionFailed error with metadata
func NewConnectionFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return ConnectionFailed.With(key, value)
}

// NewAuthenticationFailedWithMetadata creates a AuthenticationFailed error with metadata
func NewAuthenticationFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return AuthenticationFailed.With(key, value)
}

// NewSubscriptionFailedWithMetadata creates a SubscriptionFailed error with metadata
func NewSubscriptionFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return SubscriptionFailed.With(key, value)
}

// NewPublishFailedWithMetadata creates a PublishFailed error with metadata
func NewPublishFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return PublishFailed.With(key, value)
}

// NewInvalidTopicWithMetadata creates a InvalidTopic error with metadata
func NewInvalidTopicWithMetadata(key string, value interface{}) *gerr.Error {
	return InvalidTopic.With(key, value)
}

// NewClientNotConnectedWithMetadata creates a ClientNotConnected error with metadata
func NewClientNotConnectedWithMetadata(key string, value interface{}) *gerr.Error {
	return ClientNotConnected.With(key, value)
}

// NewReconnectFailedWithMetadata creates a ReconnectFailed error with metadata
func NewReconnectFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return ReconnectFailed.With(key, value)
}

// NewTLSConfigErrorWithMetadata creates a TLSConfigError error with metadata
func NewTLSConfigErrorWithMetadata(key string, value interface{}) *gerr.Error {
	return TLSConfigError.With(key, value)
}

// NewWillMessageErrorWithMetadata creates a WillMessageError error with metadata
func NewWillMessageErrorWithMetadata(key string, value interface{}) *gerr.Error {
	return WillMessageError.With(key, value)
}

// NewQosNotSupportedWithMetadata creates a QosNotSupported error with metadata
func NewQosNotSupportedWithMetadata(key string, value interface{}) *gerr.Error {
	return QosNotSupported.With(key, value)
}

// NewMessageTooLargeWithMetadata creates a MessageTooLarge error with metadata
func NewMessageTooLargeWithMetadata(key string, value interface{}) *gerr.Error {
	return MessageTooLarge.With(key, value)
}

// NewBrokerUnavailableWithMetadata creates a BrokerUnavailable error with metadata
func NewBrokerUnavailableWithMetadata(key string, value interface{}) *gerr.Error {
	return BrokerUnavailable.With(key, value)
}

// NewProtocolErrorWithMetadata creates a ProtocolError error with metadata
func NewProtocolErrorWithMetadata(key string, value interface{}) *gerr.Error {
	return ProtocolError.With(key, value)
}

// NewTimeoutErrorWithMetadata creates a TimeoutError error with metadata
func NewTimeoutErrorWithMetadata(key string, value interface{}) *gerr.Error {
	return TimeoutError.With(key, value)
}

// NewAlreadySubscribedWithMetadata creates a AlreadySubscribed error with metadata
func NewAlreadySubscribedWithMetadata(key string, value interface{}) *gerr.Error {
	return AlreadySubscribed.With(key, value)
}

// NewNotSubscribedWithMetadata creates a NotSubscribed error with metadata
func NewNotSubscribedWithMetadata(key string, value interface{}) *gerr.Error {
	return NotSubscribed.With(key, value)
}

// NewInvalidPayloadWithMetadata creates a InvalidPayload error with metadata
func NewInvalidPayloadWithMetadata(key string, value interface{}) *gerr.Error {
	return InvalidPayload.With(key, value)
}

// ConfigurationErrorF indicates this error requires format arguments
// Usage: ConfigurationErrorF.Args("ErrMessage")
var ConfigurationErrorF = ConfigurationError

// NewConfigurationErrorWithArgs creates a ConfigurationError error with arguments
func NewConfigurationErrorWithArgs(args ...interface{}) *gerr.Error {
	return ConfigurationError.Args(args...)
}

// NewConfigurationErrorWithMetadata creates a ConfigurationError error with metadata
func NewConfigurationErrorWithMetadata(key string, value interface{}) *gerr.Error {
	return ConfigurationError.With(key, value)
}

// SubscriptionNotActiveF indicates this error requires format arguments
// Usage: SubscriptionNotActiveF.Args("ErrMessage")
var SubscriptionNotActiveF = SubscriptionNotActive

// NewSubscriptionNotActiveWithArgs creates a SubscriptionNotActive error with arguments
func NewSubscriptionNotActiveWithArgs(args ...interface{}) *gerr.Error {
	return SubscriptionNotActive.Args(args...)
}

// NewSubscriptionNotActiveWithMetadata creates a SubscriptionNotActive error with metadata
func NewSubscriptionNotActiveWithMetadata(key string, value interface{}) *gerr.Error {
	return SubscriptionNotActive.With(key, value)
}

// UnsubscribeFailedF indicates this error requires format arguments
// Usage: UnsubscribeFailedF.Args("ErrMessage")
var UnsubscribeFailedF = UnsubscribeFailed

// NewUnsubscribeFailedWithArgs creates a UnsubscribeFailed error with arguments
func NewUnsubscribeFailedWithArgs(args ...interface{}) *gerr.Error {
	return UnsubscribeFailed.Args(args...)
}

// NewUnsubscribeFailedWithMetadata creates a UnsubscribeFailed error with metadata
func NewUnsubscribeFailedWithMetadata(key string, value interface{}) *gerr.Error {
	return UnsubscribeFailed.With(key, value)
}
